In [1]:
# ########################################
# Notebook 01 – Datensichtung und -auswahl
# Projekt: Preisbewertung NL
##########################################

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os
print(os.getcwd())
print()
raw_path = "../data_raw/"
files = [f for f in os.listdir(raw_path) if f.endswith(".csv")]
files

C:\Users\sk\Documents\###Coaching - 06-2025\###Data Analyst\###StackFuel\###Weiterbildung ab 29.09.2025\Business Intelligence Specialist - V - Projektarbeit\projekt_preisbewertung_nl\notebooks

['###Bevolking_naar_leeftijd_en_geslacht_gemeente_2019_2023.csv',
 '###cbs_gemeente_code.csv',
 '###Dichtheid_inwoners_m2_gemeente.csv',
 '###Stedelijkheid_gemeenten.csv',
 '###Waarstaatjegemeente_Bevolking_gemeente_2019_2023.csv',
 'aantal_particuliere_huishoudens_gemeente_2019_2023.csv',
 'arbeidsdeelname_werkloosheid_gemeente_2019_2023.csv',
 'besteedbaar_inkomen_huishoudens_gemeente_2019_2023.csv',
 'bevolkingsdichtheid_gemeente_2019_2023.csv',
 'bevolkingsdichtheid_inkomen_gemeente_2019_2023.csv',
 'bevolking_gemiddeld_gemeente_2019_2023.csv',
 'cbs_gemeenten_provincies.csv',
 'cbs_gemeinden_niederlande_2023.csv',
 'inkomen_huishoudens_gemeente_2019_2023.csv',
 'koopwoningen_gemiddelde_prijs_gemeente_2019_2023.csv',
 'migratie_jaar_2019_2023.csv',
 'nieuwbouw_pijplijn_2019_2023.csv',
 'omgevingsdichtheid_gemeente_2019_2023.csv',
 'oppervlakte_totaal_egw_mgw_gemeente_2019_2023.csv',
 'verkochte_woningen_gemeente_2019_2023.csv',
 'woningvoorraad_bouwjaar_2015_2025_gemeente_2019_2023.csv',
 'woningvoorraad_egw_bouwjaar_gemeente_2019_2023.csv',
 'woningvoorraad_egw_oppervlakte_gemeente_2019_2023.csv',
 'woningvoorraad_egw_totaal_gemeente_2019_2023.csv',
 'woningvoorraad_mgw_bouwjaar_gemeente_2019_2023.csv',
 'woningvoorraad_mgw_oppervlakte_gemeente_2019_2023.csv',
 'woningvoorraad_mgw_totaal_gemeente_2019_2023.csv',
 'woningvoorraad_oppervlakte_gemeente_2019_2023.csv',
 'woningvoorraad_totaal_egw_mgw_oppervlakte_gemeente_2019_2023.csv',
 'woningvoorraad_totaal_gemeente_2019_2023.csv',
 'woz_waarde_gemeente_2019_2023.csv']

In [3]:
########################################
# 1.1. Gemeindschlüssel NL extrahieren (cbs_gemeente_code.xlsx)
########################################

df_codes = pd.read_excel("../data_raw/cbs_gemeente_code.xlsx")
df_codes.head()

,Identifier,DimensionGroupId,DimensionId,Index,Title,Description
0,NL01,NL,RegioS,1,Nederland,NaN
1,LD01,LD,RegioS,2,Noord-Nederland (LD),LD = Landsdeel_x000D_\n_x000D_\nNoord-Nederlan...
2,LD02,LD,RegioS,3,Oost-Nederland (LD),LD = Landsdeel_x000D_\n_x000D_\nOost-Nederland...
3,LD03,LD,RegioS,4,West-Nederland (LD),LD = Landsdeel_x000D_\n_x000D_\nWest-Nederland...
4,LD04,LD,RegioS,5,Zuid-Nederland (LD),LD = Landsdeel_x000D_\n_x000D_\nZuid-Nederland...

In [4]:
df_codes.info()
df_codes.isna().sum()
df_codes.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 434 entries, 0 to 433
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Identifier        434 non-null    object
 1   DimensionGroupId  434 non-null    object
 2   DimensionId       434 non-null    object
 3   Index             434 non-null    int64
 4   Title             434 non-null    object
 5   Description       433 non-null    object
dtypes: int64(1), object(5)
memory usage: 20.5+ KB

np.int64(0)

In [5]:
df_codes_clean = df_codes[df_codes["Identifier"].str.startswith("GM")].copy()

df_codes_clean = df_codes_clean[["Identifier", "Title"]]
df_codes_clean.columns = ["gemeentecode", "gemeentenaam"]

print(df_codes_clean.info)
print()
df_codes_clean.head(10)

<bound method DataFrame.info of     gemeentecode     gemeentenaam
57        GM1680      Aa en Hunze
58        GM0358         Aalsmeer
59        GM0197           Aalten
60        GM0059    Achtkarspelen
61        GM0482     Alblasserdam
..           ...              ...
394       GM0879          Zundert
395       GM0301          Zutphen
396       GM1896  Zwartewaterland
397       GM0642      Zwijndrecht
398       GM0193           Zwolle

[342 rows x 2 columns]>

   gemeentecode         gemeentenaam
57       GM1680          Aa en Hunze
58       GM0358             Aalsmeer
59       GM0197               Aalten
60       GM0059        Achtkarspelen
61       GM0482         Alblasserdam
62       GM0613        Albrandswaard
63       GM0361              Alkmaar
64       GM0141               Almelo
65       GM0034               Almere
66       GM0484  Alphen aan den Rijn

In [6]:
############################################
# 1.2. Bevölkerungsentwicklung nach Gemeinde (bevolking_gemiddeld_gemeente_2019_2023.csv)
############################################

df_gem_bevolk = pd.read_csv("../data_raw/bevolking_gemiddeld_gemeente_2019_2023.csv", sep=";")
df_gem_bevolk.head()

,ID,Geslacht,Leeftijd,BurgerlijkeStaat,RegioS,Perioden,GemiddeldeBevolking_2
0,2197,T001038,10000,T001019,GM1680,2019JJ00,25415.5
1,2198,T001038,10000,T001019,GM1680,2020JJ00,25422.0
2,2199,T001038,10000,T001019,GM1680,2021JJ00,25489.0
3,2200,T001038,10000,T001019,GM1680,2022JJ00,25651.5
4,2201,T001038,10000,T001019,GM1680,2023JJ00,25784.5

In [7]:
df_gem_bevolk = df_gem_bevolk[["RegioS", "Perioden", "GemiddeldeBevolking_2"]].copy()
df_gem_bevolk.columns = ["gemeentecode", "jahr", "bevolking"]
df_gem_bevolk["jahr"] = df_gem_bevolk["jahr"].str[:4].astype(int)
df_gem_bevolk.head(10)

  gemeentecode  jahr  bevolking
0       GM1680  2019    25415.5
1       GM1680  2020    25422.0
2       GM1680  2021    25489.0
3       GM1680  2022    25651.5
4       GM1680  2023    25784.5
5       GM0738  2019        NaN
6       GM0738  2020        NaN
7       GM0738  2021        NaN
8       GM0738  2022        NaN
9       GM0738  2023        NaN

In [8]:
df_gem_bevolk = df_gem_bevolk.dropna(subset=["bevolking"])

print(df_gem_bevolk.info())
print(df_gem_bevolk.isna().sum())
df_gem_bevolk.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 1749 entries, 0 to 4169
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   gemeentecode  1749 non-null   object
 1   jahr          1749 non-null   int64
 2   bevolking     1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 54.7+ KB
None
gemeentecode    0
jahr            0
bevolking       0
dtype: int64

   gemeentecode  jahr  bevolking
0        GM1680  2019    25415.5
1        GM1680  2020    25422.0
2        GM1680  2021    25489.0
3        GM1680  2022    25651.5
4        GM1680  2023    25784.5
10       GM0358  2019    31793.5
11       GM0358  2020    31925.0
12       GM0358  2021    32221.5
13       GM0358  2022    32757.5
14       GM0358  2023    33171.0

In [9]:
#######################################
# 1.3. Bevölkerungsdichte nach Gemeinde (bevolkingsdichtheid_gemeente_2019_2023.csv)
#######################################

df_bevolk_dicht = pd.read_csv("../data_raw/bevolkingsdichtheid_gemeente_2019_2023.csv", sep=";")
df_bevolk_dicht.head()

     ID Geslacht  RegioS  Perioden  Bevolkingsdichtheid_2
0  4808  T001038  GM1680  2019JJ00                   92.0
1  4809  T001038  GM1680  2020JJ00                   92.0
2  4810  T001038  GM1680  2021JJ00                   92.0
3  4811  T001038  GM1680  2022JJ00                   93.0
4  4812  T001038  GM1680  2023JJ00                   93.0

In [10]:
df_bevolk_dicht = df_bevolk_dicht[[
    "RegioS",
    "Perioden",
    "Bevolkingsdichtheid_2"
]].copy()

In [11]:
df_bevolk_dicht.columns = [
    "gemeentecode",
    "jahr",
    "bevolkingsdichtheid"
]

In [12]:
df_bevolk_dicht["jahr"] = df_bevolk_dicht["jahr"].str[:4].astype(int)

print(df_bevolk_dicht.info())
print(df_bevolk_dicht.isna().sum())
df_bevolk_dicht.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6200 entries, 0 to 6199
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   gemeentecode         6200 non-null   object
 1   jahr                 6200 non-null   int64
 2   bevolkingsdichtheid  1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 145.4+ KB
None
gemeentecode              0
jahr                      0
bevolkingsdichtheid    4451
dtype: int64

  gemeentecode  jahr  bevolkingsdichtheid
0       GM1680  2019                 92.0
1       GM1680  2020                 92.0
2       GM1680  2021                 92.0
3       GM1680  2022                 93.0
4       GM1680  2023                 93.0
5       GM1000  2019                  NaN
6       GM1000  2020                  NaN
7       GM1000  2021                  NaN
8       GM1000  2022                  NaN
9       GM1000  2023                  NaN

In [13]:
####################################
# 1.4. Privathaushalte nach Gemeinde (aantal_particuliere_huishoudens_gemeente_2019_2023.csv)
####################################

df_hh = pd.read_csv("../data_raw/aantal_particuliere_huishoudens_gemeente_2019_2023.csv", sep=";")
df_hh.head()

,ID,SamenstellingVanHetHuishouden,SoortWoonruimte,RegioS,Perioden,ParticuliereHuishoudens_1
0,544,1050010,T001621,GM1680,2019JJ00,11160
1,545,1050010,T001621,GM1680,2020JJ00,11170
2,546,1050010,T001621,GM1680,2021JJ00,11255
3,547,1050010,T001621,GM1680,2022JJ00,11325
4,548,1050010,T001621,GM1680,2023JJ00,11410

In [14]:
df_hh = df_hh[[
    "RegioS",
    "Perioden",
    "ParticuliereHuishoudens_1"
]].copy()

In [15]:
df_hh.columns = ["gemeentecode", "jahr", "haushalte"]

In [16]:
df_hh["jahr"] = df_hh["jahr"].str[:4].astype(int)

In [17]:
df_hh = df_hh.dropna(subset=["haushalte"])

In [18]:
print(df_hh.info())
print(df_hh.isna().sum())
df_hh.head(10)

<class 'pandas.core.frame.DataFrame'>
Index: 1754 entries, 0 to 2074
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   gemeentecode  1754 non-null   object
 1   jahr          1754 non-null   int64
 2   haushalte     1754 non-null   object
dtypes: int64(1), object(2)
memory usage: 54.8+ KB
None
gemeentecode    0
jahr            0
haushalte       0
dtype: int64

   gemeentecode  jahr haushalte
0        GM1680  2019     11160
1        GM1680  2020     11170
2        GM1680  2021     11255
3        GM1680  2022     11325
4        GM1680  2023     11410
10       GM0358  2019     13180
11       GM0358  2020     13295
12       GM0358  2021     13710
13       GM0358  2022     14200
14       GM0358  2023     14405

In [19]:
############################################
# 1.5.1 Gesamt-Wohnungsbestand nach Gemeinde (woningvoorraad_totaal_gemeente_2019_2023.csv)
############################################

df_woning_tot = pd.read_csv("../data_raw/woningvoorraad_totaal_gemeente_2019_2023.csv", sep=";")

df_woning_tot = df_woning_tot[["RegioS", "Perioden", "Woningvoorraad_1"]].copy()
df_woning_tot.columns = ["gemeentecode", "jahr", "woningvoorraad_total"]
df_woning_tot["jahr"] = df_woning_tot["jahr"].str[:4].astype(int)

print(df_woning_tot.info())
df_woning_tot.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070 entries, 0 to 2069
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gemeentecode          2070 non-null   object
 1   jahr                  2070 non-null   int64
 2   woningvoorraad_total  1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 48.6+ KB
None

  gemeentecode  jahr  woningvoorraad_total
0       GM1680  2019               11180.0
1       GM1680  2020               11205.0
2       GM1680  2021               11335.0
3       GM1680  2022               11430.0
4       GM1680  2023               11500.0
5       GM0738  2019                   NaN
6       GM0738  2020                   NaN
7       GM0738  2021                   NaN
8       GM0738  2022                   NaN
9       GM0738  2023                   NaN

In [20]:
#########################################
# 1.5.2 Wohnungsbestand EFH nach Gemeinde (woningvoorraad_egw_totaal_gemeente_2019_2023.csv)
#########################################

df_woning_egw_tot = pd.read_csv("../data_raw/woningvoorraad_egw_totaal_gemeente_2019_2023.csv", sep=";")

df_woning_egw_tot = df_woning_egw_tot[["RegioS", "Perioden", "Woningvoorraad_1"]].copy()
df_woning_egw_tot.columns = ["gemeentecode", "jahr", "woningvoorraad_total"]
df_woning_egw_tot["jahr"] = df_woning_egw_tot["jahr"].str[:4].astype(int)

print(df_woning_egw_tot.info())
df_woning_egw_tot.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070 entries, 0 to 2069
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gemeentecode          2070 non-null   object
 1   jahr                  2070 non-null   int64
 2   woningvoorraad_total  1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 48.6+ KB
None

  gemeentecode  jahr  woningvoorraad_total
0       GM1680  2019               10230.0
1       GM1680  2020               10260.0
2       GM1680  2021               10380.0
3       GM1680  2022               10450.0
4       GM1680  2023               10475.0
5       GM0738  2019                   NaN
6       GM0738  2020                   NaN
7       GM0738  2021                   NaN
8       GM0738  2022                   NaN
9       GM0738  2023                   NaN

In [21]:
#######################################
# 1.5.3 Wohnungsbestand MFH nach Gemeinde (woningvoorraad_mgw_totaal_gemeente_2019_2023.csv)
#######################################

df_woning_mgw_tot = pd.read_csv("../data_raw/woningvoorraad_mgw_totaal_gemeente_2019_2023.csv", sep=";")

df_woning_mgw_tot = df_woning_mgw_tot[["RegioS", "Perioden", "Woningvoorraad_1"]].copy()
df_woning_mgw_tot.columns = ["gemeentecode", "jahr", "woningvoorraad_total"]
df_woning_mgw_tot["jahr"] = df_woning_mgw_tot["jahr"].str[:4].astype(int)

print(df_woning_mgw_tot.info())
df_woning_mgw_tot.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070 entries, 0 to 2069
Data columns (total 3 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gemeentecode          2070 non-null   object
 1   jahr                  2070 non-null   int64
 2   woningvoorraad_total  1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 48.6+ KB
None

  gemeentecode  jahr  woningvoorraad_total
0       GM1680  2019                 945.0
1       GM1680  2020                 945.0
2       GM1680  2021                 955.0
3       GM1680  2022                 980.0
4       GM1680  2023                1025.0
5       GM0738  2019                   NaN
6       GM0738  2020                   NaN
7       GM0738  2021                   NaN
8       GM0738  2022                   NaN
9       GM0738  2023                   NaN

In [22]:
##########################################################
# 1.5.4 Wohnungsbestand gesamt, EFH und MFH zusammenführen
##########################################################

df_woning_full = (
    df_woning_tot
    .merge(df_woning_egw_tot, on=["gemeentecode", "jahr"], how="left")
    .merge(df_woning_mgw_tot, on=["gemeentecode", "jahr"], how="left")
)

df_woning_full = df_woning_full.rename(columns={
    "woningvoorraad_total_x": "woningvoorraad_total",
    "woningvoorraad_total_y": "woningvoorraad_egw",
    "woningvoorraad_total": "woningvoorraad_mgw"
})

print(df_woning_full.info())
print(df_woning_full.isna().sum())
df_woning_full.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070 entries, 0 to 2069
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gemeentecode          2070 non-null   object
 1   jahr                  2070 non-null   int64
 2   woningvoorraad_total  1749 non-null   float64
 3   woningvoorraad_egw    1749 non-null   float64
 4   woningvoorraad_mgw    1749 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 81.0+ KB
None
gemeentecode              0
jahr                      0
woningvoorraad_total    321
woningvoorraad_egw      321
woningvoorraad_mgw      321
dtype: int64

,gemeentecode,jahr,woningvoorraad_total,woningvoorraad_egw,woningvoorraad_mgw
0,GM1680,2019,11180.0,10230.0,945.0
1,GM1680,2020,11205.0,10260.0,945.0
2,GM1680,2021,11335.0,10380.0,955.0
3,GM1680,2022,11430.0,10450.0,980.0
4,GM1680,2023,11500.0,10475.0,1025.0
5,GM0738,2019,NaN,NaN,NaN
6,GM0738,2020,NaN,NaN,NaN
7,GM0738,2021,NaN,NaN,NaN
8,GM0738,2022,NaN,NaN,NaN
9,GM0738,2023,NaN,NaN,NaN

In [23]:
###################################################
# 1.6. Wohnfläche gesamt, EFH und MFH nach Gemeinde (woningvoorraad_oppervlakte_gemeente_2019_2023.csv)
###################################################

df_oppervlakte = pd.read_csv("../data_raw/woningvoorraad_oppervlakte_gemeente_2019_2023.csv", sep=";")
df_oppervlakte.head(10)

,ID,Woningtype,Oppervlakteklasse,RegioS,Perioden,BeginstandWoningvoorraad_1
0,847,T001100,T001116,GM1680,2019JJ00,11257.0
1,848,T001100,T001116,GM1680,2020JJ00,11179.0
2,849,T001100,T001116,GM1680,2021JJ00,11207.0
3,850,T001100,T001116,GM1680,2022JJ00,11336.0
4,851,T001100,T001116,GM1680,2023JJ00,11428.0
5,861,T001100,T001116,GM0738,2019JJ00,NaN
6,862,T001100,T001116,GM0738,2020JJ00,NaN
7,863,T001100,T001116,GM0738,2021JJ00,NaN
8,864,T001100,T001116,GM0738,2022JJ00,NaN
9,865,T001100,T001116,GM0738,2023JJ00,NaN

In [24]:
df_oppervlakte["BeginstandWoningvoorraad_1"] = pd.to_numeric(
    df_oppervlakte["BeginstandWoningvoorraad_1"], errors="coerce"
)

df_op_clean = (
    df_oppervlakte
    .groupby(["Woningtype", "RegioS", "Perioden"])["BeginstandWoningvoorraad_1"]
    .sum()
    .reset_index()
)

df_op_clean["jahr"] = df_op_clean["Perioden"].str[:4].astype(int)

In [25]:
df_op_tot = df_op_clean[df_op_clean["Woningtype"] == "T001100"][
    ["RegioS", "jahr", "BeginstandWoningvoorraad_1"]
].rename(columns={
    "RegioS": "gemeentecode",
    "BeginstandWoningvoorraad_1": "oppervlakte_totaal"
})

df_op_egw = df_op_clean[df_op_clean["Woningtype"] == "ZW10290"][
    ["RegioS", "jahr", "BeginstandWoningvoorraad_1"]
].rename(columns={
    "RegioS": "gemeentecode",
    "BeginstandWoningvoorraad_1": "oppervlakte_egw"
})

df_op_mgw = df_op_clean[df_op_clean["Woningtype"] == "ZW10340"][
    ["RegioS", "jahr", "BeginstandWoningvoorraad_1"]
].rename(columns={
    "RegioS": "gemeentecode",
    "BeginstandWoningvoorraad_1": "oppervlakte_mgw"
})

In [26]:
df_op_full = (
    df_op_tot
    .merge(df_op_egw, on=["gemeentecode", "jahr"], how="left")
    .merge(df_op_mgw, on=["gemeentecode", "jahr"], how="left")
)

print(df_op_full.info())
print(df_op_full.isna().sum())
df_op_full.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2210 entries, 0 to 2209
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gemeentecode        2210 non-null   object
 1   jahr                2210 non-null   int64
 2   oppervlakte_totaal  2210 non-null   float64
 3   oppervlakte_egw     2210 non-null   float64
 4   oppervlakte_mgw     2210 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 86.5+ KB
None
gemeentecode          0
jahr                  0
oppervlakte_totaal    0
oppervlakte_egw       0
oppervlakte_mgw       0
dtype: int64

  gemeentecode  jahr  oppervlakte_totaal  oppervlakte_egw  oppervlakte_mgw
0       GM0000  2019                 0.0              0.0              0.0
1       GM0000  2020                 0.0              0.0              0.0
2       GM0000  2021                 0.0              0.0              0.0
3       GM0000  2022                 0.0              0.0              0.0
4       GM0000  2023                 0.0              0.0              0.0
5       GM0003  2019              6032.0           4372.0           1660.0
6       GM0003  2020              6042.0           4381.0           1661.0
7       GM0003  2021                 0.0              0.0              0.0
8       GM0003  2022                 0.0              0.0              0.0
9       GM0003  2023                 0.0              0.0              0.0

In [27]:
####################################################
# 1.7. Verfügbares Einkommen Haushalte nach Gemeinde (besteedbaar_inkomen_huishoudens_gemeente_2019_2023.csv)
####################################################

df_income_raw = pd.read_csv("../data_raw/besteedbaar_inkomen_huishoudens_gemeente_2019_2023.csv", sep=";")
df_income_raw.head(10)

,ID,Populatie,KenmerkenVanHuishoudens,RegioS,Perioden,GemiddeldBesteedbaarInkomen_5,MediaanBesteedbaarInkomen_6
0,806,1050010,1050010,GM1680,2019JJ00,47.4,41.4
1,807,1050010,1050010,GM1680,2020JJ00,49.1,43.4
2,808,1050010,1050010,GM1680,2021JJ00,51.6,45.6
3,809,1050010,1050010,GM1680,2022JJ00,53.6,47.4
4,810,1050010,1050010,GM1680,2023JJ00,59.1,51.0
5,820,1050010,1050010,GM0358,2019JJ00,58.0,46.2
6,821,1050010,1050010,GM0358,2020JJ00,58.7,47.7
7,822,1050010,1050010,GM0358,2021JJ00,61.2,49.4
8,823,1050010,1050010,GM0358,2022JJ00,63.4,51.2
9,824,1050010,1050010,GM0358,2023JJ00,76.3,53.8

In [28]:
df_income = df_income_raw.copy()

df_income["jahr"] = df_income["Perioden"].str[:4].astype(int)

df_income_clean = df_income[[
    "RegioS",
    "jahr",
    "GemiddeldBesteedbaarInkomen_5",
    "MediaanBesteedbaarInkomen_6"
]].rename(columns={
    "RegioS": "gemeentecode",
    "GemiddeldBesteedbaarInkomen_5": "inkomen_gemiddeld",
    "MediaanBesteedbaarInkomen_6": "inkomen_mediaan"
})

df_income_clean["inkomen_gemiddeld"] = df_income_clean["inkomen_gemiddeld"] * 1000
df_income_clean["inkomen_mediaan"] = df_income_clean["inkomen_mediaan"] * 1000

In [29]:
print(df_income_clean.info())
print(df_income_clean.isna().sum())
df_income_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3420 entries, 0 to 3419
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gemeentecode       3420 non-null   object
 1   jahr               3420 non-null   int64
 2   inkomen_gemiddeld  3420 non-null   float64
 3   inkomen_mediaan    3420 non-null   float64
dtypes: float64(2), int64(1), object(1)
memory usage: 107.0+ KB
None
gemeentecode         0
jahr                 0
inkomen_gemiddeld    0
inkomen_mediaan      0
dtype: int64

  gemeentecode  jahr  inkomen_gemiddeld  inkomen_mediaan
0       GM1680  2019            47400.0          41400.0
1       GM1680  2020            49100.0          43400.0
2       GM1680  2021            51600.0          45600.0
3       GM1680  2022            53600.0          47400.0
4       GM1680  2023            59100.0          51000.0
5       GM0358  2019            58000.0          46200.0
6       GM0358  2020            58700.0          47700.0
7       GM0358  2021            61200.0          49400.0
8       GM0358  2022            63400.0          51200.0
9       GM0358  2023            76300.0          53800.0

In [30]:
###############################
# 1.8. WOZ-Waarde nach Gemeinde (woz_waarde_gemeente_2019_2023.csv)
###############################

df_woz_raw = pd.read_csv("../data_raw/woz_waarde_gemeente_2019_2023.csv", sep=";")
df_woz_raw.head(10)

     ID  RegioS Eigendom  Perioden  GemiddeldeWOZWaardeVanWoningen_1
0  1596  GM1680  T001132  2019JJ00                             241.0
1  1597  GM1680  T001132  2020JJ00                             257.0
2  1598  GM1680  T001132  2021JJ00                             271.0
3  1599  GM1680  T001132  2022JJ00                             298.0
4  1600  GM1680  T001132  2023JJ00                             342.0
5  1624  GM0358  T001132  2019JJ00                             337.0
6  1625  GM0358  T001132  2020JJ00                             361.0
7  1626  GM0358  T001132  2021JJ00                             383.0
8  1627  GM0358  T001132  2022JJ00                             427.0
9  1628  GM0358  T001132  2023JJ00                             494.0

In [31]:
df_woz = df_woz_raw.copy()

df_woz["jahr"] = df_woz["Perioden"].str[:4].astype(int)

df_woz_clean = df_woz[[
    "RegioS",
    "jahr",
    "GemiddeldeWOZWaardeVanWoningen_1"
]].rename(columns={
    "RegioS": "gemeentecode",
    "GemiddeldeWOZWaardeVanWoningen_1": "woz_gemiddeld"
})

df_woz_clean["woz_gemiddeld"] = df_woz_clean["woz_gemiddeld"] * 1000

In [32]:
print(df_woz_clean.info())
print(df_woz_clean.isna().sum())
df_woz_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gemeentecode   1800 non-null   object
 1   jahr           1800 non-null   int64
 2   woz_gemiddeld  1749 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 42.3+ KB
None
gemeentecode      0
jahr              0
woz_gemiddeld    51
dtype: int64

  gemeentecode  jahr  woz_gemiddeld
0       GM1680  2019       241000.0
1       GM1680  2020       257000.0
2       GM1680  2021       271000.0
3       GM1680  2022       298000.0
4       GM1680  2023       342000.0
5       GM0358  2019       337000.0
6       GM0358  2020       361000.0
7       GM0358  2021       383000.0
8       GM0358  2022       427000.0
9       GM0358  2023       494000.0

In [33]:
#####################################
# 1.9. Baugenehmigungen nach Gemeinde (nieuwbouw_pijplijn_2019_2023.csv)
#####################################

df_bouwvergunningen_raw = pd.read_csv("../data_raw/nieuwbouw_pijplijn_2019_2023.csv", sep=";")
df_bouwvergunningen_raw.head(10)

,ID,Gebruiksfunctie,RegioS,Perioden,VerblijfsobjectenInDePijplijnTotaal_1,BouwGestartPijplijn_2,Vergunningspijplijn_3
0,100129,A045364,GM1680,2019JJ00,96.0,21.0,75.0
1,100146,A045364,GM1680,2020JJ00,155.0,23.0,132.0
2,100163,A045364,GM1680,2021JJ00,98.0,21.0,77.0
3,100180,A045364,GM1680,2022JJ00,90.0,25.0,65.0
4,100197,A045364,GM1680,2023JJ00,88.0,50.0,38.0
5,100316,A045364,GM0738,2019JJ00,NaN,NaN,NaN
6,100333,A045364,GM0738,2020JJ00,NaN,NaN,NaN
7,100350,A045364,GM0738,2021JJ00,NaN,NaN,NaN
8,100367,A045364,GM0738,2022JJ00,NaN,NaN,NaN
9,100384,A045364,GM0738,2023JJ00,NaN,NaN,NaN

In [34]:
df_bouwverg = df_bouwvergunningen_raw.copy()

df_bouwverg["jahr"] = df_bouwverg["Perioden"].str[:4].astype(int)

df_bouwverg_clean = df_bouwverg[[
    "RegioS", "jahr",
    "VerblijfsobjectenInDePijplijnTotaal_1",
    "BouwGestartPijplijn_2",
    "Vergunningspijplijn_3"
]].rename(columns={
    "RegioS": "gemeentecode",
    "VerblijfsobjectenInDePijplijnTotaal_1": "pipeline_total",
    "BouwGestartPijplijn_2": "pipeline_started",
    "Vergunningspijplijn_3": "pipeline_permit"
})

In [35]:
print(df_bouwverg_clean.info())
print(df_bouwverg_clean.isna().sum())
df_bouwverg_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2075 entries, 0 to 2074
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gemeentecode      2075 non-null   object
 1   jahr              2075 non-null   int64
 2   pipeline_total    1754 non-null   float64
 3   pipeline_started  1754 non-null   float64
 4   pipeline_permit   1754 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 81.2+ KB
None
gemeentecode          0
jahr                  0
pipeline_total      321
pipeline_started    321
pipeline_permit     321
dtype: int64

  gemeentecode  jahr  pipeline_total  pipeline_started  pipeline_permit
0       GM1680  2019            96.0              21.0             75.0
1       GM1680  2020           155.0              23.0            132.0
2       GM1680  2021            98.0              21.0             77.0
3       GM1680  2022            90.0              25.0             65.0
4       GM1680  2023            88.0              50.0             38.0
5       GM0738  2019             NaN               NaN              NaN
6       GM0738  2020             NaN               NaN              NaN
7       GM0738  2021             NaN               NaN              NaN
8       GM0738  2022             NaN               NaN              NaN
9       GM0738  2023             NaN               NaN              NaN

In [36]:
##############################################################
# 1.10.1 Entwicklung Wohnungsbestand 2015 - 2025 nach Gemeinde (woningvoorraad_bouwjaar_2015_2025_gemeente_2019_2023.csv)
##############################################################

df_bouwjaar_2015_2025_raw = pd.read_csv("../data_raw/woningvoorraad_bouwjaar_2015_2025_gemeente_2019_2023.csv", sep=";")
df_bouwjaar_2015_2025_raw.head(10)

,ID,Woningtype,Bouwjaarklasse,RegioS,Perioden,BeginstandWoningvoorraad_1,GemiddeldeOppervlakte_2
0,85183,T001100,ZW25825,GM1680,2019JJ00,127.0,146
1,85184,T001100,ZW25825,GM1680,2020JJ00,158.0,145
2,85185,T001100,ZW25825,GM1680,2021JJ00,172.0,146
3,85186,T001100,ZW25825,GM1680,2022JJ00,308.0,146
4,85187,T001100,ZW25825,GM1680,2023JJ00,376.0,157
5,85197,T001100,ZW25825,GM0738,2019JJ00,NaN,NaN
6,85198,T001100,ZW25825,GM0738,2020JJ00,NaN,NaN
7,85199,T001100,ZW25825,GM0738,2021JJ00,NaN,NaN
8,85200,T001100,ZW25825,GM0738,2022JJ00,NaN,NaN
9,85201,T001100,ZW25825,GM0738,2023JJ00,NaN,NaN

In [37]:
df_bouwjaar = df_bouwjaar_2015_2025_raw.copy()

# Jahr extrahieren
df_bouwjaar["jahr"] = df_bouwjaar["Perioden"].str[:4].astype(int)

# Relevante Variablen auswählen und umbenennen
df_bouwjaar_clean = df_bouwjaar[[
    "RegioS",
    "jahr",
    "Woningtype",
    "BeginstandWoningvoorraad_1",
    "GemiddeldeOppervlakte_2"
]].rename(columns={
    "RegioS": "gemeentecode",
    "BeginstandWoningvoorraad_1": "nieuwbouw_bestand",
    "GemiddeldeOppervlakte_2": "nieuwbouw_oppervlakte"
})

In [38]:
print(df_bouwjaar_clean.info())
print(df_bouwjaar_clean.isna().sum())
df_bouwjaar_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6630 entries, 0 to 6629
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gemeentecode           6630 non-null   object
 1   jahr                   6630 non-null   int64
 2   Woningtype             6630 non-null   object
 3   nieuwbouw_bestand      5262 non-null   float64
 4   nieuwbouw_oppervlakte  5262 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 259.1+ KB
None
gemeentecode                0
jahr                        0
Woningtype                  0
nieuwbouw_bestand        1368
nieuwbouw_oppervlakte    1368
dtype: int64

  gemeentecode  jahr Woningtype  nieuwbouw_bestand nieuwbouw_oppervlakte
0       GM1680  2019    T001100              127.0                   146
1       GM1680  2020    T001100              158.0                   145
2       GM1680  2021    T001100              172.0                   146
3       GM1680  2022    T001100              308.0                   146
4       GM1680  2023    T001100              376.0                   157
5       GM0738  2019    T001100                NaN                   NaN
6       GM0738  2020    T001100                NaN                   NaN
7       GM0738  2021    T001100                NaN                   NaN
8       GM0738  2022    T001100                NaN                   NaN
9       GM0738  2023    T001100                NaN                   NaN

In [39]:
##############################################################
# 1.10.2 Entwicklung Wohnungsbestand 2015 - 2025 nach Gemeinde - Aufsplittung nach Wohnungstyp
##############################################################

# Totaal
df_bouwjaar_tot = df_bouwjaar_clean[df_bouwjaar_clean["Woningtype"] == "T001100"].drop(columns=["Woningtype"])
df_bouwjaar_tot = df_bouwjaar_tot.rename(columns={
    "nieuwbouw_bestand": "nieuwbouw_bestand_tot",
    "nieuwbouw_oppervlakte": "nieuwbouw_oppervlakte_tot"
})

# EGW
df_bouwjaar_egw = df_bouwjaar_clean[df_bouwjaar_clean["Woningtype"] == "ZW10290"].drop(columns=["Woningtype"])
df_bouwjaar_egw = df_bouwjaar_egw.rename(columns={
    "nieuwbouw_bestand": "nieuwbouw_bestand_egw",
    "nieuwbouw_oppervlakte": "nieuwbouw_oppervlakte_egw"
})

# MGW
df_bouwjaar_mgw = df_bouwjaar_clean[df_bouwjaar_clean["Woningtype"] == "ZW10340"].drop(columns=["Woningtype"])
df_bouwjaar_mgw = df_bouwjaar_mgw.rename(columns={
    "nieuwbouw_bestand": "nieuwbouw_bestand_mgw",
    "nieuwbouw_oppervlakte": "nieuwbouw_oppervlakte_mgw"
})

In [40]:
##############################################################
# 1.10.3 Entwicklung Wohnungsbestand 2015 - 2025 nach Gemeinde - Merge (totaal, egw und mgw)
##############################################################

df_bouwjaar_full = (
    df_bouwjaar_tot
    .merge(df_bouwjaar_egw, on=["gemeentecode", "jahr"], how="left")
    .merge(df_bouwjaar_mgw, on=["gemeentecode", "jahr"], how="left")
)

In [41]:
print(df_bouwjaar_full.info())
print(df_bouwjaar_full.isna().sum())
df_bouwjaar_full.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2210 entries, 0 to 2209
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   gemeentecode               2210 non-null   object
 1   jahr                       2210 non-null   int64
 2   nieuwbouw_bestand_tot      1754 non-null   float64
 3   nieuwbouw_oppervlakte_tot  1754 non-null   object
 4   nieuwbouw_bestand_egw      1754 non-null   float64
 5   nieuwbouw_oppervlakte_egw  1754 non-null   object
 6   nieuwbouw_bestand_mgw      1754 non-null   float64
 7   nieuwbouw_oppervlakte_mgw  1754 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 138.3+ KB
None
gemeentecode                   0
jahr                           0
nieuwbouw_bestand_tot        456
nieuwbouw_oppervlakte_tot    456
nieuwbouw_bestand_egw        456
nieuwbouw_oppervlakte_egw    456
nieuwbouw_bestand_mgw        456
nieuwbouw_oppervlakte_mgw    456
dtype: int64

,gemeentecode,jahr,nieuwbouw_bestand_tot,nieuwbouw_oppervlakte_tot,nieuwbouw_bestand_egw,nieuwbouw_oppervlakte_egw,nieuwbouw_bestand_mgw,nieuwbouw_oppervlakte_mgw
0,GM1680,2019,127.0,146,121.0,147,6.0,.
1,GM1680,2020,158.0,145,152.0,145,6.0,.
2,GM1680,2021,172.0,146,166.0,146,6.0,.
3,GM1680,2022,308.0,146,292.0,149,16.0,.
4,GM1680,2023,376.0,157,360.0,160,16.0,.
5,GM0738,2019,NaN,NaN,NaN,NaN,NaN,NaN
6,GM0738,2020,NaN,NaN,NaN,NaN,NaN,NaN
7,GM0738,2021,NaN,NaN,NaN,NaN,NaN,NaN
8,GM0738,2022,NaN,NaN,NaN,NaN,NaN,NaN
9,GM0738,2023,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
for col in [
    "nieuwbouw_oppervlakte_tot",
    "nieuwbouw_oppervlakte_egw",
    "nieuwbouw_oppervlakte_mgw"
]:
    df_bouwjaar_full[col] = (
        df_bouwjaar_full[col]
        .astype(str)                # alles in Strings
        .str.strip()                # whitespace entfernen
        .replace({"." : np.nan})    # Punkt → NaN
        .replace({"": np.nan})      # leere Strings → NaN
        .astype(float)              # jetzt sicher konvertieren
    )

df_bouwjaar_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2210 entries, 0 to 2209
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   gemeentecode               2210 non-null   object
 1   jahr                       2210 non-null   int64
 2   nieuwbouw_bestand_tot      1754 non-null   float64
 3   nieuwbouw_oppervlakte_tot  1746 non-null   float64
 4   nieuwbouw_bestand_egw      1754 non-null   float64
 5   nieuwbouw_oppervlakte_egw  1735 non-null   float64
 6   nieuwbouw_bestand_mgw      1754 non-null   float64
 7   nieuwbouw_oppervlakte_mgw  1605 non-null   float64
dtypes: float64(6), int64(1), object(1)
memory usage: 138.3+ KB

In [43]:
#############################################################
# 1.11. Erwerbsbeteiligung und Arbeitslosigkeit nach Gemeinde (arbeidsdeelname_werkloosheid_gemeente_2019_2023.csv)
#############################################################

df_arbeid_raw = pd.read_csv("../data_raw/arbeidsdeelname_werkloosheid_gemeente_2019_2023.csv", sep=";")
df_arbeid_raw.head(10)

,ID,Persoonskenmerken,RegioS,Perioden,Werkloosheidspercentage_13,BrutoArbeidsparticipatie_15,NettoArbeidsparticipatie_16
0,760,T009002,GM1680,2019JJ00,3.7,70.3,67.7
1,761,T009002,GM1680,2020JJ00,4.2,69.9,67.0
2,762,T009002,GM1680,2021JJ00,3.4,70.9,68.6
3,763,T009002,GM1680,2022JJ00,3.0,72.4,70.2
4,764,T009002,GM1680,2023JJ00,2.7,73.4,71.4
5,773,T009002,GM0358,2019JJ00,3.5,77.6,74.9
6,774,T009002,GM0358,2020JJ00,4.2,77.8,74.6
7,775,T009002,GM0358,2021JJ00,3.8,78.0,75.1
8,776,T009002,GM0358,2022JJ00,3.0,79.5,77.1
9,777,T009002,GM0358,2023JJ00,3.1,80.9,78.4

In [44]:
df_arbeid = df_arbeid_raw.copy()

# Jahr extrahieren
df_arbeid["jahr"] = df_arbeid["Perioden"].str[:4].astype(int)

# Relevante Spalten auswählen und umbenennen
df_arbeid_clean = df_arbeid[[
    "RegioS",
    "jahr",
    "Werkloosheidspercentage_13",
    "BrutoArbeidsparticipatie_15",
    "NettoArbeidsparticipatie_16"
]].rename(columns={
    "RegioS": "gemeentecode",
    "Werkloosheidspercentage_13": "arbeitslosigkeit",
    "BrutoArbeidsparticipatie_15": "arbeidsparticipatie_bruto",
    "NettoArbeidsparticipatie_16": "arbeidsparticipatie_netto"
})

df_arbeid_clean["beschaeftigungsquote"] = (
    100 - df_arbeid_clean["arbeitslosigkeit"]
)

print(df_arbeid_clean.info())
print(df_arbeid_clean.isna().sum())
df_arbeid_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1710 entries, 0 to 1709
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   gemeentecode               1710 non-null   object
 1   jahr                       1710 non-null   int64
 2   arbeitslosigkeit           1710 non-null   float64
 3   arbeidsparticipatie_bruto  1710 non-null   float64
 4   arbeidsparticipatie_netto  1710 non-null   float64
 5   beschaeftigungsquote       1710 non-null   float64
dtypes: float64(4), int64(1), object(1)
memory usage: 80.3+ KB
None
gemeentecode                 0
jahr                         0
arbeitslosigkeit             0
arbeidsparticipatie_bruto    0
arbeidsparticipatie_netto    0
beschaeftigungsquote         0
dtype: int64

,gemeentecode,jahr,arbeitslosigkeit,arbeidsparticipatie_bruto,arbeidsparticipatie_netto,beschaeftigungsquote
0,GM1680,2019,3.7,70.3,67.7,96.3
1,GM1680,2020,4.2,69.9,67.0,95.8
2,GM1680,2021,3.4,70.9,68.6,96.6
3,GM1680,2022,3.0,72.4,70.2,97.0
4,GM1680,2023,2.7,73.4,71.4,97.3
5,GM0358,2019,3.5,77.6,74.9,96.5
6,GM0358,2020,4.2,77.8,74.6,95.8
7,GM0358,2021,3.8,78.0,75.1,96.2
8,GM0358,2022,3.0,79.5,77.1,97.0
9,GM0358,2023,3.1,80.9,78.4,96.9

In [45]:
###############################
# 1.12. Migration nach Gemeinde (migratie_jaar_2019_2023.csv)
###############################

df_migratie_raw = pd.read_csv("../data_raw/migratie_jaar_2019_2023.csv", sep=";")
df_migratie_raw.head(10)

,ID,Geslacht,RegioS,Perioden,BevolkingOp1Januari_1,BevolkingOp31December_20
0,4808,T001038,GM1680,2019JJ00,25386.0,25445.0
1,4809,T001038,GM1680,2020JJ00,25445.0,25399.0
2,4810,T001038,GM1680,2021JJ00,25399.0,25579.0
3,4811,T001038,GM1680,2022JJ00,25579.0,25724.0
4,4812,T001038,GM1680,2023JJ00,25724.0,25845.0
5,4891,T001038,GM1000,2019JJ00,NaN,NaN
6,4892,T001038,GM1000,2020JJ00,NaN,NaN
7,4893,T001038,GM1000,2021JJ00,NaN,NaN
8,4894,T001038,GM1000,2022JJ00,NaN,NaN
9,4895,T001038,GM1000,2023JJ00,NaN,NaN

In [46]:
df_migr = df_migratie_raw.copy()

# Jahr extrahieren
df_migr["jahr"] = df_migr["Perioden"].str[:4].astype(int)

# Relevante Spalten auswählen und umbenennen
df_migr_clean = df_migr[[
    "RegioS",
    "jahr",
    "BevolkingOp1Januari_1",
    "BevolkingOp31December_20"
]].rename(columns={
    "RegioS": "gemeentecode",
    "BevolkingOp1Januari_1": "bev_1jan",
    "BevolkingOp31December_20": "bev_31dec"
})

print(df_migr_clean.info())
print(df_migr_clean.isna().sum())
df_migr_clean.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6200 entries, 0 to 6199
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   gemeentecode  6200 non-null   object
 1   jahr          6200 non-null   int64
 2   bev_1jan      1749 non-null   float64
 3   bev_31dec     1748 non-null   float64
dtypes: float64(2), int64(1), object(1)
memory usage: 193.9+ KB
None
gemeentecode       0
jahr               0
bev_1jan        4451
bev_31dec       4452
dtype: int64

  gemeentecode  jahr  bev_1jan  bev_31dec
0       GM1680  2019   25386.0    25445.0
1       GM1680  2020   25445.0    25399.0
2       GM1680  2021   25399.0    25579.0
3       GM1680  2022   25579.0    25724.0
4       GM1680  2023   25724.0    25845.0
5       GM1000  2019       NaN        NaN
6       GM1000  2020       NaN        NaN
7       GM1000  2021       NaN        NaN
8       GM1000  2022       NaN        NaN
9       GM1000  2023       NaN        NaN

In [47]:
# Vorbereitung Berechnung Migration
df_migr_clean["netto_migration"] = (
    df_migr_clean["bev_31dec"] - df_migr_clean["bev_1jan"]
)

# Migration pro 1000 Einwohner
df_migr_clean["migration_pro_1000"] = (
    df_migr_clean["netto_migration"] / df_migr_clean["bev_1jan"] * 1000
)

# Migrationsquote in %
df_migr_clean["migration_quote"] = (
    df_migr_clean["netto_migration"] / df_migr_clean["bev_1jan"] * 100
)

df_migr_clean.head()

,gemeentecode,jahr,bev_1jan,bev_31dec,netto_migration,migration_pro_1000,migration_quote
0,GM1680,2019,25386.0,25445.0,59.0,2.324116,0.232412
1,GM1680,2020,25445.0,25399.0,-46.0,-1.807821,-0.180782
2,GM1680,2021,25399.0,25579.0,180.0,7.086893,0.708689
3,GM1680,2022,25579.0,25724.0,145.0,5.668713,0.566871
4,GM1680,2023,25724.0,25845.0,121.0,4.703779,0.470378

In [48]:
##############################################
# 1.13.1 Verkaufspreis Wohnungen nach Gemeinde (koopwoningen_gemiddelde_prijs_gemeente_2019_2023.csv)
##############################################

df_verkoop_raw = pd.read_csv("../data_raw/koopwoningen_gemiddelde_prijs_gemeente_2019_2023.csv", sep=";")
print(df_verkoop_raw.shape)
df_verkoop_raw.head(10)

(3640, 4)

    ID  RegioS  Perioden  GemiddeldeVerkoopprijs_1
0  551  GM1680  2019JJ00                  284794.0
1  552  GM1680  2020JJ00                  303789.0
2  553  GM1680  2021JJ00                  393780.0
3  554  GM1680  2022JJ00                  407982.0
4  555  GM1680  2023JJ00                  411021.0
5  582  GM0738  2019JJ00                       NaN
6  583  GM0738  2020JJ00                       NaN
7  584  GM0738  2021JJ00                       NaN
8  585  GM0738  2022JJ00                       NaN
9  586  GM0738  2023JJ00                       NaN

In [49]:
####################################################
# 1.13.2 Proxy - Anteile Wohnungstypen nach Gemeinde (oppervlakte_totaal_egw_mgw_gemeente_2019_2023.csv)
####################################################

df_woning_type_raw = pd.read_csv("../data_raw/oppervlakte_totaal_egw_mgw_gemeente_2019_2023.csv", sep=";")
print(df_woning_type_raw.shape)
df_woning_type_raw.head(10)

(6630, 7)

,ID,Woningtype,Bouwjaarklasse,RegioS,Perioden,BeginstandWoningvoorraad_1,GemiddeldeOppervlakte_2
0,847,T001100,T001018,GM1680,2019JJ00,11257.0,165
1,848,T001100,T001018,GM1680,2020JJ00,11179.0,166
2,849,T001100,T001018,GM1680,2021JJ00,11207.0,166
3,850,T001100,T001018,GM1680,2022JJ00,11336.0,166
4,851,T001100,T001018,GM1680,2023JJ00,11428.0,183
5,861,T001100,T001018,GM0738,2019JJ00,NaN,NaN
6,862,T001100,T001018,GM0738,2020JJ00,NaN,NaN
7,863,T001100,T001018,GM0738,2021JJ00,NaN,NaN
8,864,T001100,T001018,GM0738,2022JJ00,NaN,NaN
9,865,T001100,T001018,GM0738,2023JJ00,NaN,NaN

In [50]:
# Kopie für sauberes Arbeiten
df_wt = df_woning_type_raw.copy()

# Jahr extrahieren
df_wt["year"] = df_wt["Perioden"].str[:4].astype(int)

# EGW extrahieren
df_egw = df_wt[df_wt["Woningtype"] == "ZW10290"].rename(
    columns={
        "BeginstandWoningvoorraad_1": "stock_egw",
        "GemiddeldeOppervlakte_2": "avg_area_egw"
    }
)[["RegioS", "year", "stock_egw", "avg_area_egw"]]

# MGW extrahieren
df_mgw = df_wt[df_wt["Woningtype"] == "ZW10340"].rename(
    columns={
        "BeginstandWoningvoorraad_1": "stock_mgw",
        "GemiddeldeOppervlakte_2": "avg_area_mgw"
    }
)[["RegioS", "year", "stock_mgw", "avg_area_mgw"]]

# Merge EGW + MGW
df_structure = df_egw.merge(df_mgw, on=["RegioS", "year"], how="outer")

print(df_structure.shape)
df_structure.head(10)

(2210, 6)

   RegioS  year  stock_egw avg_area_egw  stock_mgw avg_area_mgw
0  GM0000  2019        0.0            .        0.0            .
1  GM0000  2020        0.0            .        0.0            .
2  GM0000  2021        0.0            .        0.0            .
3  GM0000  2022        0.0            .        0.0            .
4  GM0000  2023        0.0            .        0.0            .
5  GM0003  2019     4372.0          132     1660.0           80
6  GM0003  2020     4381.0          132     1661.0           80
7  GM0003  2021        NaN          NaN        NaN          NaN
8  GM0003  2022        NaN          NaN        NaN          NaN
9  GM0003  2023        NaN          NaN        NaN          NaN

In [51]:
import numpy as np

# Alle relevanten Spalten als Strings behandeln und sauber konvertieren
for col in ["stock_egw", "avg_area_egw", "stock_mgw", "avg_area_mgw"]:
    df_structure[col] = (
        df_structure[col]
        .astype(str)          # alles als String
        .str.strip()          # Leerzeichen entfernen
        .replace(".", np.nan) # "." → NaN
        .replace("", np.nan)  # leere Strings → NaN
        .astype(float)        # in float umwandeln
    )

In [52]:
df_structure_step2 = df_structure.copy()

# 1. Bestandsanteile
df_structure_step2["share_egw"] = (
    df_structure_step2["stock_egw"] /
    (df_structure_step2["stock_egw"] + df_structure_step2["stock_mgw"])
)

df_structure_step2["share_mgw"] = 1 - df_structure_step2["share_egw"]

# 2. Verhältnis der Durchschnittsflächen
df_structure_step2["ratio_avg_area"] = (
    df_structure_step2["avg_area_egw"] /
    df_structure_step2["avg_area_mgw"]
)

# 3. Verhältnis der Bestandszahlen
df_structure_step2["ratio_stock"] = (
    df_structure_step2["stock_egw"] /
    df_structure_step2["stock_mgw"]
)

print(df_structure_step2.shape)
df_structure_step2.head(10)

(2210, 10)

,RegioS,year,stock_egw,avg_area_egw,stock_mgw,avg_area_mgw,share_egw,share_mgw,ratio_avg_area,ratio_stock
0,GM0000,2019,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
1,GM0000,2020,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2,GM0000,2021,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
3,GM0000,2022,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,GM0000,2023,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN
5,GM0003,2019,4372.0,132.0,1660.0,80.0,0.724801,0.275199,1.65,2.633735
6,GM0003,2020,4381.0,132.0,1661.0,80.0,0.725091,0.274909,1.65,2.637568
7,GM0003,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GM0003,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,GM0003,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df_structure_step3 = df_structure_step2.copy()

df_structure_step3["ratio_price"] = (
    0.6 * df_structure_step3["ratio_avg_area"] +
    0.4 * df_structure_step3["ratio_stock"]
)

print(df_structure_step3.shape)
df_structure_step3.head(10)

(2210, 11)

,RegioS,year,stock_egw,avg_area_egw,stock_mgw,avg_area_mgw,share_egw,share_mgw,ratio_avg_area,ratio_stock,ratio_price
0,GM0000,2019,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,GM0000,2020,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,GM0000,2021,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,GM0000,2022,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,GM0000,2023,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
5,GM0003,2019,4372.0,132.0,1660.0,80.0,0.724801,0.275199,1.65,2.633735,2.043494
6,GM0003,2020,4381.0,132.0,1661.0,80.0,0.725091,0.274909,1.65,2.637568,2.045027
7,GM0003,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GM0003,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,GM0003,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
# Jahr extrahieren in df_verkoop_raw
df_verkoop_raw["year"] = df_verkoop_raw["Perioden"].str[:4].astype(int)

# Merge Struktur + Preise
df_full = df_structure_step3.merge(
    df_verkoop_raw[["RegioS", "year", "GemiddeldeVerkoopprijs_1"]],
    on=["RegioS", "year"],
    how="left"
)

df_full["price_egw"] = (
    df_full["GemiddeldeVerkoopprijs_1"] *
    df_full["ratio_price"] /
    (df_full["share_egw"] * df_full["ratio_price"] + df_full["share_mgw"])
)

df_full["price_mgw"] = df_full["price_egw"] / df_full["ratio_price"]

df_full["ratio_price_realized"] = df_full["price_egw"] / df_full["price_mgw"]

print(df_full.shape)
df_full.head(10)

(2210, 15)

,RegioS,year,stock_egw,avg_area_egw,stock_mgw,avg_area_mgw,share_egw,share_mgw,ratio_avg_area,ratio_stock,ratio_price,GemiddeldeVerkoopprijs_1,price_egw,price_mgw,ratio_price_realized
0,GM0000,2019,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GM0000,2020,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,GM0000,2021,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GM0000,2022,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GM0000,2023,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,GM0003,2019,4372.0,132.0,1660.0,80.0,0.724801,0.275199,1.65,2.633735,2.043494,194795.0,226645.003884,110910.53194,2.043494
6,GM0003,2020,4381.0,132.0,1661.0,80.0,0.725091,0.274909,1.65,2.637568,2.045027,204754.0,238219.265648,116487.09524,2.045027
7,GM0003,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,GM0003,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,GM0003,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
# 1. Kopie von df_full erstellen
df_full_harm = df_full.copy()

# 2. Spalten harmonisieren
df_full_harm = df_full_harm.rename(columns={
    "RegioS": "municipality_code",
    "GemiddeldeVerkoopprijs_1": "price_total",
    "ratio_avg_area": "ratio_area",
    "ratio_price": "ratio_price_model",
    "stock_egw": "housing_stock_egw",
    "stock_mgw": "housing_stock_mgw"
})

# 3. Verhältnis price_egw / price_mgw hinzufügen
df_full_harm["ratio_price_realized"] = df_full_harm["price_egw"] / df_full_harm["price_mgw"]

# 4. Dummy-Gemeinden entfernen
df_full_harm = df_full_harm[df_full_harm["municipality_code"] != "GM0000"]

# 5. Zeilen ohne Strukturinformationen entfernen
df_full_harm = df_full_harm.dropna(subset=["housing_stock_egw", "housing_stock_mgw"])

# 6. Spalten sortieren
df_full_harm = df_full_harm[[
    "municipality_code", "year",
    "price_total", "price_egw", "price_mgw",
    "ratio_price_model", "ratio_price_realized",
    "share_egw", "share_mgw",
    "housing_stock_egw", "housing_stock_mgw",
    "ratio_area", "ratio_stock"
]]

print(df_full_harm.shape)
df_full_harm.head(10)

(1749, 13)

,municipality_code,year,price_total,price_egw,price_mgw,ratio_price_model,ratio_price_realized,share_egw,share_mgw,housing_stock_egw,housing_stock_mgw,ratio_area,ratio_stock
5,GM0003,2019,194795.0,226645.003884,110910.531940,2.043494,2.043494,0.724801,0.275199,4372.0,1660.0,1.650000,2.633735
6,GM0003,2020,204754.0,238219.265648,116487.095240,2.045027,2.045027,0.725091,0.274909,4381.0,1661.0,1.650000,2.637568
25,GM0010,2019,155120.0,179051.446218,68997.509703,2.595042,2.595042,0.782548,0.217452,9533.0,2649.0,1.925926,3.598716
26,GM0010,2020,177054.0,204527.400500,79319.580100,2.578523,2.578523,0.780578,0.219422,9541.0,2682.0,1.925926,3.557420
30,GM0014,2019,258873.0,298670.074524,231956.101359,1.287615,1.287615,0.403467,0.596533,46291.0,68442.0,1.695122,0.676354
31,GM0014,2020,278720.0,324057.808009,248388.656185,1.304640,1.304640,0.400842,0.599158,46676.0,69769.0,1.728395,0.669008
32,GM0014,2021,321804.0,377909.627110,284872.000572,1.326594,1.326594,0.396958,0.603042,47207.0,71715.0,1.772152,0.658258
33,GM0014,2022,353917.0,420269.442461,310809.858184,1.352175,1.352175,0.393818,0.606182,47535.0,73168.0,1.820513,0.649669
34,GM0014,2023,349931.0,417685.371080,306594.600316,1.362338,1.362338,0.390099,0.609901,47871.0,74844.0,1.844156,0.639610
55,GM0024,2019,192374.0,207430.975620,39007.948328,5.317659,5.317659,0.910600,0.089400,4278.0,420.0,2.072289,10.185714

In [56]:
########################################################################
# 1.14. Begriffe vereinheitlichen und Dataframes als csv-Datei speichern
########################################################################

# 1. Gemeindeschlüssel
df_codes_clean = df_codes_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jaar": "year"
})

# 2. Bevölkerungsentwicklung
df_gem_bevolk = df_gem_bevolk.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "bevolking": "population"
})

# 3. Bevölkerungsdichte (Einheit: Einwohner pro km²)
df_bevolk_dicht = df_bevolk_dicht.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "bevolkingdichtheid": "population_density"
})

# 4. Haushalte
df_hh = df_hh.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "haushalte": "households"
})

# 5. Wohnungsbestand
df_woning_full = df_woning_full.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "woningvoorraad_totaal": "housing_stock_total",
    "woningvoorraad_egw": "housing_stock_egw",
    "woningvoorraad_mgw": "housing_stock_mgw"
})

#6. Wohnfläche
df_op_full = df_op_full.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "oppervlakte_totaal": "living_space_total",
    "oppervlakte_egw": "living_space_egw",
    "oppervlakte_mgw": "living_space_mgw"
})

#7. Einkommen
df_income_clean = df_income_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "inkomen_gemiddeld": "income_mean",
    "inkomen_mediaan": "income_median"
})

#8. WOZ-waarde (es gibt keine anderen WOZ-waarde-Kennziffern)
df_woz_clean = df_woz_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "woz_gemiddeld": "woz_mean"
})

#9. Baugenehmigungen
df_bouwverg_clean = df_bouwverg_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "pipeline_total": "pipeline_total",
    "pipeline_started": "pipeline_started",
    "pipeline_permit": "pipeline_permit"
})

#10. Entwicklung Wohnungsbestand
df_bouwjaar_full = df_bouwjaar_full. rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "nieuwbouw_bestand_tot": "new_build_stock_tot",
    "nieuwbouw_oppervlakte_tot": "new_build_liv_space_tot",
    "nieuwbouw_bestand_egw": "new_build_stock_egw",
    "nieuwbouw_oppervlakte_egw": "new_build_liv_space_egw",
    "nieuwbouw_bestand_mgw": "new_build_stock_mgw",
    "nieuwbouw_oppervlakte_mgw": "new_build_liv_space_mgw"
})

#11. Erwerbstätigkeit und Arbeitslosigkeit
df_arbeid_clean = df_arbeid_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "arbeitslosigkeit": "unemployment_rate",
    "arbeidsparticipatie_bruto": "labor_participation_gross",
    "arbeidsparticipatie_netto": "labor_participation_net",
    "beschaeftigungsquote": "employment_rate"
})

#12. Migration
df_migr_clean = df_migr_clean.rename(columns={
    "gemeentecode": "municipality_code",
    "jahr": "year",
    "bev_1jan": "population_jan1",
    "bev_31dec": "population_dec31",
    "netto_migration": "migration_net",
    "migration_pro_1000": "migration_per_1000",
    "migration_quote": "migration_rate"
})

In [57]:
import os

os.makedirs("../data_clean", exist_ok=True)

dfs_to_save = {
    "df_full_harm": df_full_harm,
    "df_codes_clean": df_codes_clean,
    "df_gem_bevolk": df_gem_bevolk,
    "df_bevolk_dicht": df_bevolk_dicht,
    "df_hh": df_hh,
    "df_woning_full": df_woning_full,
    "df_op_full": df_op_full,
    "df_income_clean": df_income_clean,
    "df_woz_clean": df_woz_clean,
    "df_bouwverg_clean": df_bouwverg_clean,
    "df_bouwjaar_full": df_bouwjaar_full,
    "df_arbeid_clean": df_arbeid_clean,
    "df_migr_clean": df_migr_clean
}

for name, df in dfs_to_save.items():
    path = f"../data_clean/{name}.csv"
    df.to_csv(path, index=False)
    if os.path.exists(path):
        print(f"✔️ {name}.csv gespeichert.")
    else:
        print(f"❌ Fehler beim Speichern von {name}.csv")

✔️ df_full_harm.csv gespeichert.
✔️ df_codes_clean.csv gespeichert.
✔️ df_gem_bevolk.csv gespeichert.
✔️ df_bevolk_dicht.csv gespeichert.
✔️ df_hh.csv gespeichert.
✔️ df_woning_full.csv gespeichert.
✔️ df_op_full.csv gespeichert.
✔️ df_income_clean.csv gespeichert.
✔️ df_woz_clean.csv gespeichert.
✔️ df_bouwverg_clean.csv gespeichert.
✔️ df_bouwjaar_full.csv gespeichert.
✔️ df_arbeid_clean.csv gespeichert.
✔️ df_migr_clean.csv gespeichert.